server:
  port: 8080

spring:
  application:
    name: course
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL122Dialect
  jmx:
    enable: false
  datasource:
    url: jdbc:postgresql://localhost:5432/devdojo?allowPublicKeyRetrieval=true&sslMode=DISABLED
    username: postgres
    password: devdojo