server:
  port: 8082

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:8081/eureka/
    register-with-eureka: true

spring:
  application:
    name: course
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  jmx:
    enable: false
  datasource:
    url: jdbc:postgresql://localhost:5432/devdojo?allowPublicKeyRetrieval=true&sslMode=DISABLED
    username: postgres
    password: root

jwt:
  config:
    type: signed #only need signed Token (saves internal processing). To increase security (encrypted + signed) remove this line.